# -*- coding: utf-8 -*-
"""ICSGenerator_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCvnst5zFiTtvKriCWBUcB8hv_33zjJB
"""

# Paste this into a local Python 3 file (e.g., make_ics.py) and run:  python make_ics.py
from datetime import datetime, timedelta

dates = [
    "1-Apr","2-Apr","3-Apr","4-Apr","5-Apr","6-Apr","7-Apr","8-Apr",
    "9-Apr","10-Apr","11-Apr","12-Apr","13-Apr","14-Apr","15-Apr","16-Apr",
    "17-Apr","18-Apr","19-Apr","20-Apr","21-Apr","22-Apr","23-Apr","24-Apr",
    "25-Apr","26-Apr","27-Apr","28-Apr","29-Apr","30-Apr"
]

names = [
    "Lakshmi Prasanna","Abishek Selvaraj","Sathiesh M","Tamanna Tyagi",
    "Kundan Verma","Lalit Kumar","Shashi Patil","Mitali Jha",
    "Poojitha Sankrana","Chamundi P","Diksha","Supreetha",
    "Adhila P","Nirmalraj C","Hansika S"
]

shifts = {

    "Lakshmi Prasanna": [
        "S1","S1","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1","OFF",
        "OFF","S3","S3","S3","S3","S3","OFF","OFF","S1","S1","S1","S1","S1","OFF"
    ],

    "Abishek Selvaraj": [
        "OFF","OFF","L","S3","S3","S3","S3","S3","OFF","OFF","S2","S2","S2","S2","S2","OFF",
        "OFF","S1","S1","S1","S1","S1","L","OFF","S2","S2","S2","S2","S2","OFF"
    ],

    "Sathiesh M": [
        "S1","S1","S1","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S3","S3","S3","S3",
        "S3","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1"
    ],

    "Tamanna Tyagi": [
        "S2","S2","OFF","S3","S3","OFF","OFF","S2","S2","S2","OFF","OFF","S2","S2","S2","S2",
        "OFF","OFF","S1","S1","S1","S1","S1","OFF","OFF","S1","S1","S1","S1","S3"
    ],

    "Kundan Verma": [
        "S3","S3","S3","OFF","OFF","OFF","S1","S1","S1","S1","S1","OFF","OFF","PH","S1","S1",
        "S1","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S2","S2","S2","S1"
    ],

    "Lalit Kumar": [
        "S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1","OFF","S2","S2","S2","S2",
        "OFF","S3","S3","OFF","OFF","S2","S3","S3","OFF","OFF","S2","S2","S2","S2"
    ],

    "Shashi Patil": [
        "S1","S1","S1","OFF","OFF","S2","S2","S2","OFF","OFF","S1","S1","S1","S1","S1","OFF",
        "S1","OFF","OFF","L","L","L","L","L","S3","S3","S3","S3","S3","OFF"
    ],

    "Mitali Jha": [
        "S2","S2","S2","S2","S2","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S2","S2",
        "S2","OFF","OFF","S1","S1","S1","S1","OFF","S3","S3","OFF","OFF","S2","S2"
    ],

    "Poojitha Sankrana": [
        "OFF","S1","S1","S1","S1","S1","OFF","OFF","S3","S3","S3","S3","OFF","OFF","S2","S2",
        "S2","S2","S2","OFF","OFF","S1","S1","S1","L","OFF","L","L","L","L"
    ],

    "Chamundi P": [
        "S2","OFF","OFF","S1","S1","S1","L","S1","S1","S1","OFF","OFF","S1","S1","OFF","OFF",
        "S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1","S1","OFF","S2"
    ],

    "Diksha": [
        "S2","S2","S2","OFF","OFF","S1","S1","S1","S1","OFF","S3","S3","OFF","OFF","S1","S1",
        "S1","S1","OFF","S1","S1","OFF","OFF","S2","S2","S2","S2","S2","L","L"
    ],

    "Supreetha": [
        "S3","S3","S3","OFF","OFF","S1","S1","S1","S1","S1","OFF","OFF","S2","S2","S2","S2",
        "S2","OFF","OFF","S1","S1","S1","S1","S1","OFF","OFF","S2","S2","S2","S2"
    ],

    "Adhila P": [
        "S3","S3","S3","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1",
        "S1","OFF","OFF","S2","S2","S2","S2","S2","OFF","OFF","S1","S1","S1","S1"
    ],

    "Nirmalraj C": [
        "S2","L","S2","EVE","OFF","S2","S2","S2","S2","S2","OFF","OFF","S2","PH","S2","S2",
        "S2","EVE","OFF","S2","S2","S2","S2","S2","OFF","OFF","S2","S2","S2","S2"
    ],

    "Hansika S": [
        "S2","S2","S2","OFF","OFF","S2","S2","S2","S2","S2","EVE","OFF","S2","S2","S2","S2",
        "S2","OFF","OFF","S2","S2","S2","S2","S2","EVE","OFF","S2","S2","S2","S2"
    ]
}




def dtfmt(dt): return dt.strftime("%Y%m%dT%H%M%S")
shift_time = {
    "S1": ("06:00", "15:30"),
    "G": ("09:00", "18:30"),
    "S2": ("14:00", "23:30"),
    "EVE": ("17:00", "02:30"),
    "S3": ("22:00", "07:30")
}

WORKING_SHIFTS = {"S1", "G", "S2", "EVE", "S3"}

lines = ["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Shift Calendar//Sathiesh M//EN"]

for i, d in enumerate(dates):
    sath = shifts["Sathiesh M"][i]
    ymd = datetime.strptime(f"{d}-2026", "%d-%b-%Y")
    lines.append("BEGIN:VEVENT")

    if sath in shift_time:
        st, et = shift_time[sath]
        start_dt = datetime.strptime(f"{ymd:%Y-%m-%d} {st}", "%Y-%m-%d %H:%M")
        end_dt = datetime.strptime(f"{ymd:%Y-%m-%d} {et}", "%Y-%m-%d %H:%M")

        if sath in ("S3", "EVE"):
            end_dt += timedelta(days=1)

        lines.append(f"DTSTART;TZID=Asia/Kolkata:{dtfmt(start_dt)}")
        lines.append(f"DTEND;TZID=Asia/Kolkata:{dtfmt(end_dt)}")
        lines.append(f"SUMMARY:{sath} ({st}–{et})")

        # --- description builder ---
        same, prev, nex, g_eve = [], [], [], []

        for nm in names:
            if nm == "Sathiesh M":
                continue

            today_shift = shifts[nm][i]

            if today_shift == sath:
                same.append(nm)

            if today_shift in ("G", "EVE"):
                g_eve.append(f"{nm} ({today_shift})")

        # rotation logic
        if sath == "S1":
            if i > 0:
                prev = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i-1] == "S3"]
            nex = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i] == "S2"]

        elif sath == "S2":
            prev = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i] == "S1"]
            nex = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i] == "S3"]

        elif sath == "S3":
            prev = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i] == "S2"]
            if i < len(dates) - 1:
                nex = [nm for nm in names if nm != "Sathiesh M" and shifts[nm][i+1] == "S1"]

        desc = ["Colleagues in same shift:"]
        desc += [f"- {n}" for n in same]

        if g_eve:
            desc += ["", "Colleagues in G / EVE:"]
            desc += [f"- {n}" for n in g_eve]

        desc += ["", "Previous shift:"]
        desc += [f"- {n}" for n in prev]

        desc += ["", "Next shift:"]
        desc += [f"- {n}" for n in nex]

        lines.append("DESCRIPTION:" + "\\n".join(desc))

    else:
        start_date = ymd.strftime("%Y%m%d")
        end_date = (ymd + timedelta(days=1)).strftime("%Y%m%d")
        lines.append(f"DTSTART;VALUE=DATE:{start_date}")
        lines.append(f"DTEND;VALUE=DATE:{end_date}")
        lines.append("SUMMARY:" + ("Leave" if sath == "L" else "Off"))

        working = [
            f"{nm} ({shifts[nm][i]})"
            for nm in names
            if shifts[nm][i] in WORKING_SHIFTS
        ]

        desc = ["Working colleagues today:"]
        desc += [f"- {w}" for w in working]
        lines.append("DESCRIPTION:" + "\\n".join(desc))

        if sath == "OFF":
            lines.append("COLOR:#33B679")
            lines.append("X-GOOGLE-CALENDAR-COLOR:#33B679")

    lines.append("END:VEVENT")


lines.append("END:VCALENDAR")

ics_text = "\n".join(lines)
print(ics_text)